// Numerics validation: run the C++ draft graph with inputs generated by
// gen_oracle.py (PyTorch reference) and compare against the expected output.
//
// Usage:
//   test_vs_oracle <model.safetensors> <oracle_dir>
//
// oracle_dir must contain: noise.bin, target.bin, expected.bin, meta.txt
// Exit 0 on success (cos_sim >= 0.9999 and max_abs_diff < 1e-2 in bf16 regime).

#include "dflash27b.h"
#include "internal.h"
#include "draft_graph.h"

#include "ggml.h"
#include "ggml-alloc.h"
#include "ggml-backend.h"
#include "ggml-cuda.h"

#include <cinttypes>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <string>
#include <vector>

using namespace dflash::common;

struct OracleMeta {
    int ctx_len = 0;
    int q_len = 0;
    int hidden = 0;
    int fc_in = 0;
};

static bool read_meta(const std::string & path, OracleMeta & m) {
    std::ifstream f(path);
    if (!f) return false;
    std::string line;
    while (std::getline(f, line)) {
        auto eq = line.find('=');
        if (eq == std::string::npos) continue;
        std::string k = line.substr(0, eq);
        int v = std::atoi(line.c_str() + eq + 1);
        if      (k == "ctx_len") m.ctx_len = v;
        else if (k == "q_len")   m.q_len   = v;
        else if (k == "hidden")  m.hidden  = v;
        else if (k == "fc_in")   m.fc_in   = v;
    }
    return m.ctx_len > 0 && m.q_len > 0 && m.hidden > 0 && m.fc_in > 0;
}

static std::vector<float> read_bin_f32(const std::string & path) {
    std::ifstream f(path, std::ios::binary | std::ios::ate);
    if (!f) return {};
    auto sz = (size_t)f.tellg();
    f.seekg(0);
    std::vector<float> out(sz / sizeof(float));
    f.read((char *)out.data(), sz);
    return out;
}

int main(int argc, char ** argv) {
    if (argc < 3) {
        std::fprintf(stderr, "usage: %s <model.safetensors> <oracle_dir>\n", argv[0]);
        return 2;
    }
    const std::string draft_path = argv[1];
    const std::string oracle_dir = argv[2];

    OracleMeta m;
    if (!read_meta(oracle_dir + "/meta.txt", m)) {
        std::fprintf(stderr, "failed to read meta.txt\n");
        return 1;
    }
    std::printf("meta: ctx_len=%d q_len=%d hidden=%d fc_in=%d\n",
                m.ctx_len, m.q_len, m.hidden, m.fc_in);

    auto noise_host    = read_bin_f32(oracle_dir + "/noise.bin");
    auto target_host   = read_bin_f32(oracle_dir + "/target.bin");
    auto expected_host = read_bin_f32(oracle_dir + "/expected.bin");
    if (noise_host.empty() || target_host.empty() || expected_host.empty()) {
        std::fprintf(stderr, "failed to read oracle bins\n");
        return 1;
    }

    const size_t exp_noise  = (size_t)m.q_len * m.hidden;
    const size_t exp_target = (size_t)m.ctx_len * m.fc_in;
    const size_t exp_out    = (size_t)m.q_len * m.hidden;
    if (noise_host.size() != exp_noise || target_host.size() != exp_target ||
        expected_host.size() != exp_out) {
        std::fprintf(stderr, "bin size mismatch: noise=%zu/%zu target=%zu/%zu exp=%zu/%zu\n",
            noise_host.size(), exp_noise, target_host.size(), exp_target,
            expected_host.size(), exp_out);
        return 1;
    }

    // Backend + weights
    ggml_backend_t backend = ggml_backend_cuda_init(0);
    if (!backend) { std::fprintf(stderr, "cuda init failed\n"); return 1; }
    DraftWeights w;
    if (!load_draft_safetensors(draft_path, backend, w)) {
        std::fprintf(stderr, "load: %s\n", dflash27b_last_error());
        return 1;
    }

    // Graph context
    ggml_init_params ip{};
    ip.mem_size   = 256 * 1024 * 1024;
    ip.mem_buffer = nullptr;
    ip.no_alloc   = true;
    ggml_context * gctx = ggml_init(ip);

    ggml_tensor * noise_embed = ggml_new_tensor_3d(gctx, GGML_TYPE_F32, m.hidden, m.q_len, 1);
    ggml_tensor * target_hid  = ggml_new_tensor_3d(gctx, GGML_TYPE_F32, m.fc_in, m.ctx_len, 1);
    ggml_tensor * pos_q       = ggml_new_tensor_1d(gctx, GGML_TYPE_I32, m.q_len);
    ggml_tensor * pos_k       = ggml_new_tensor_1d(gctx, GGML_TYPE_I32, m.ctx_len + m.q_len);
    ggml_set_name(noise_embed, "noise_embed");
    ggml_set_name(target_hid,  "target_hidden_cat");
    ggml_set_name(pos_q,       "positions_q");
    ggml_set_name(pos_k,       "positions_k");
    ggml_set_input(noise_embed);
    ggml_set_input(target_hid);
    ggml_set_input(pos_q);
    ggml_set_input(pos_k);

    DraftGraphInputs gi{};
    gi.ctx_len = m.ctx_len;
    gi.noise_embed = noise_embed;
    gi.target_hidden_cat = target_hid;
    gi.positions_q = pos_q;
    gi.positions_k = pos_k;
    DraftGraphOutputs go = build_draft_graph(gctx, w, gi);
    if (!go.hidden_states) return 1;
    ggml_set_output(go.hidden_states);

    ggml_cgraph * gf = ggml_new_graph(gctx);
    ggml_build_forward_expand(gf, go.hidden_states);

    ggml_gallocr_t alloc = ggml_gallocr_new(ggml_backend_get_default_buffer_type(backend));
    if (!ggml_gallocr_alloc_graph(alloc, gf)) {
        std::fprintf(stderr, "alloc graph failed\n");
        return 1;
    }

    // Upload inputs
    ggml_backend_tensor_set(noise_embed, noise_host.data(), 0, sizeof(float) * noise_host.size());
    ggml_backend_tensor_set(target_hid,  target_host.data(), 0, sizeof(float) * target_host.size());

    std::vector<int32_t> pq(m.q_len), pk(m.ctx_len + m.q_len);
    for (int i = 0; i < m.q_len; i++)           pq[i] = m.ctx_len + i;
    for (int i = 0; i < m.ctx_len + m.q_len; i++) pk[i] = i;
    ggml_backend_tensor_set(pos_q, pq.data(), 0, sizeof(int32_t) * pq.size());
    ggml_backend_tensor_set(pos_k, pk.data(), 0, sizeof(int32_t) * pk.size());

    // Compute
    auto status = ggml_backend_graph_compute(backend, gf);
    if (status != GGML_STATUS_SUCCESS) {
        std::fprintf(stderr, "compute failed: %d\n", (int)status);
        return 1;
    }

    // Read output
    std::vector<float> got(exp_out);
    ggml_backend_tensor_get(go.hidden_states, got.data(), 0, sizeof(float) * got.size());

    // Cosine similarity + max abs diff + mean abs diff
    double dot = 0.0, na = 0.0, nb = 0.0;
    double max_abs_diff = 0.0, sum_abs_diff = 0.0;
    int n_finite = 0;
    for (size_t i = 0; i < got.size(); i++) {
        float a = got[i], b = expected_host[i];
        if (!std::isfinite(a) || !std::isfinite(b)) continue;
        n_finite++;
        dot += (double)a * b;
        na += (double)a * a;
        nb += (double)b * b;
        double d = std::fabs((double)a - b);
        if (d > max_abs_diff) max_abs_diff = d;
        sum_abs_diff += d;
    }
    double cos_sim = dot / std::sqrt(na * nb + 1e-20);
    double mean_abs_diff = sum_abs_diff / std::max(1, n_finite);

    std::printf("n=%zu finite=%d\n", got.size(), n_finite);
    std::printf("cos_sim      = %.10f\n", cos_sim);
    std::printf("max_abs_diff = %.6g\n", max_abs_diff);
    std::printf("mean_abs_diff= %.6g\n", mean_abs_diff);

    std::printf("got first 8 : ");
    for (int i = 0; i < 8; i++) std::printf("%.4f ", got[i]);
    std::printf("\nexp first 8 : ");
    for (int i = 0; i < 8; i++) std::printf("%.4f ", expected_host[i]);
    std::printf("\n");

    // Pass if cos_sim is very high. Threshold is permissive because the
    // reference runs in bf16 on GPU and our graph also mixes bf16 weights
    // with f32 activations — bit-exact is not expected, but cos_sim should
    // be very close to 1.
    const double MIN_COS_SIM = 0.999;
    int rc = (cos_sim >= MIN_COS_SIM) ? 0 : 1;
    std::printf("%s\n", rc == 0 ? "PASS" : "FAIL");

    ggml_gallocr_free(alloc);
    ggml_free(gctx);
    free_draft_weights(w);
    ggml_backend_free(backend);
    return rc;
}
