"""B.6: agent-loop bench using real Claude Code session messages.

Extracts the first N user-text turns from a session JSONL, replays them
sequentially through the dflash server, and reports per-turn latency
under two configs: prefix-cache enabled vs disabled.

Usage:
    python3 dflash/scripts/bench_agent_loop.py [--turns N] [--session PATH]

Default session = most recent JSONL under
~/.claude/projects/-home-peppi-Dev-lucebox-hub/.

Each turn's user text is the real human prompt from the session. Assistant
replies are generated by the dflash server (small max_tokens to keep
the bench fast); the synthesized history grows turn-by-turn.

Compares cold (--prefix-cache-slots=0) vs warm (--prefix-cache-slots=4).
Reports total wall time, per-turn latency, and per-turn ratio.
"""
import argparse
import json
import os
import signal
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

ROOT          = Path(__file__).resolve().parent.parent.parent
TARGET        = Path.home() / "models/qwen3.6-27b/Qwen3.6-27B-UD-Q4_K_XL.gguf"
DRAFT         = Path.home() / "models/qwen3.6-27b-dflash"
BIN           = ROOT / "dflash/build/test_dflash"
SERVER_SCRIPT = ROOT / "dflash/scripts/server.py"
SESSION_DIR   = Path.home() / ".claude/projects/-home-peppi-Dev-lucebox-hub"


def extract_user_turns(jsonl_path: Path, limit: int) -> list[str]:
    """Pull the first `limit` user-text messages from a Claude Code session."""
    turns = []
    with open(jsonl_path) as f:
        for ln in f:
            try:
                rec = json.loads(ln)
            except json.JSONDecodeError:
                continue
            if rec.get("type") != "user":
                continue
            msg = rec.get("message", {})
            content = msg.get("content", "")
            if isinstance(content, str) and content.strip() and not content.startswith("<"):
                # Skip command-name records (they start with <command-message> etc).
                turns.append(content.strip())
                if len(turns) >= limit:
                    break
    return turns


def chat_post(port: int, payload: dict, timeout=600) -> str:
    body = json.dumps(payload).encode()
    req = urllib.request.Request(
        f"http://127.0.0.1:{port}/v1/chat/completions",
        data=body, headers={"Content-Type": "application/json"})
    resp = urllib.request.urlopen(req, timeout=timeout)
    data = json.loads(resp.read())
    return data["choices"][0]["message"]["content"]


def wait_server_up(port: int, proc: subprocess.Popen, timeout=180) -> bool:
    deadline = time.time() + timeout
    while time.time() < deadline:
        if proc.poll() is not None:
            return False
        try:
            urllib.request.urlopen(f"http://127.0.0.1:{port}/v1/models", timeout=1).read()
            return True
        except (urllib.error.URLError, ConnectionResetError, TimeoutError):
            time.sleep(1)
    return False


def run_config(label: str, port: int, slots: int, user_turns: list[str],
                max_tokens: int, log_path: Path) -> list[float]:
    """Spin up server with --prefix-cache-slots=slots, replay turns, return latencies."""
    log_f = open(log_path, "w")
    proc = subprocess.Popen(
        [sys.executable, "-u", str(SERVER_SCRIPT),
         "--target", str(TARGET), "--draft", str(DRAFT), "--bin", str(BIN),
         "--max-ctx", "4096", "--port", str(port),
         "--prefix-cache-slots", str(slots)],
        stdout=log_f, stderr=subprocess.STDOUT, bufsize=1)

    if not wait_server_up(port, proc):
        log_f.close()
        out = log_path.read_text()[-1500:]
        proc.send_signal(signal.SIGINT)
        try: proc.wait(timeout=10)
        except subprocess.TimeoutExpired: proc.kill()
        raise RuntimeError(f"{label}: server didn't come up\n{out}")

    print(f"\n--- {label} (slots={slots}) ---", flush=True)

    history = []
    SYSTEM = "You are a precise coding assistant for the lucebox-hub repo. Answer concisely."
    latencies = []
    try:
        for i, user_text in enumerate(user_turns):
            history.append({"role": "user", "content": user_text})
            msgs = [{"role": "system", "content": SYSTEM}, *history]
            payload = {"model": "luce-dflash", "messages": msgs,
                       "max_tokens": max_tokens, "stream": False}
            t0 = time.time()
            try:
                reply = chat_post(port, payload, timeout=300)
            except Exception as e:
                print(f"  turn {i+1}: ERROR {e}")
                latencies.append(float("nan"))
                continue
            dt = time.time() - t0
            latencies.append(dt)
            history.append({"role": "assistant", "content": reply})
            print(f"  turn {i+1}: {dt:.2f}s  reply={reply[:50]!r}", flush=True)
    finally:
        proc.send_signal(signal.SIGINT)
        try: proc.wait(timeout=10)
        except subprocess.TimeoutExpired: proc.kill()
        log_f.close()

    return latencies


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--turns", type=int, default=5,
                    help="Number of user turns to replay")
    ap.add_argument("--max-tokens", type=int, default=8,
                    help="max_tokens per response (kept small to bound bench time)")
    ap.add_argument("--session", type=Path, default=None,
                    help="Path to session JSONL; default = most recent under "
                         f"{SESSION_DIR}")
    args = ap.parse_args()

    if not TARGET.exists() or not BIN.exists():
        print(f"SKIP: prereqs missing (target={TARGET.exists()} bin={BIN.exists()})")
        return 0

    if args.session:
        session = args.session
    else:
        candidates = sorted(SESSION_DIR.glob("*.jsonl"),
                            key=lambda p: p.stat().st_mtime, reverse=True)
        if not candidates:
            print(f"No session JSONL under {SESSION_DIR}")
            return 1
        session = candidates[0]
    print(f"Session: {session.name}", flush=True)

    user_turns = extract_user_turns(session, args.turns)
    if len(user_turns) < args.turns:
        print(f"Only got {len(user_turns)} turns")
    print(f"Extracted {len(user_turns)} user turns:")
    for i, t in enumerate(user_turns):
        print(f"  [{i+1}] {t[:80]!r}{'...' if len(t)>80 else ''}")

    # Cold config: cache disabled (slots=0) → every turn re-prefills full history
    cold = run_config("COLD (cache disabled)", port=18290, slots=0,
                       user_turns=user_turns, max_tokens=args.max_tokens,
                       log_path=Path("/tmp/bench_cold.log"))

    # Warm config: cache enabled (slots=4) → multi-point inline-snap
    warm = run_config("WARM (cache enabled)", port=18291, slots=4,
                       user_turns=user_turns, max_tokens=args.max_tokens,
                       log_path=Path("/tmp/bench_warm.log"))

    print("\n=== Per-turn latency ===", flush=True)
    print(f"{'turn':>4} {'cold':>8} {'warm':>8} {'speedup':>8}")
    total_cold = total_warm = 0.0
    for i, (c, w) in enumerate(zip(cold, warm), start=1):
        speedup = (c / w) if (w and w > 0) else float("nan")
        print(f"{i:>4} {c:>8.2f} {w:>8.2f} {speedup:>7.2f}x")
        total_cold += c; total_warm += w
    overall = total_cold / total_warm if total_warm else float("nan")
    print(f"\ntotal_cold={total_cold:.2f}s  total_warm={total_warm:.2f}s  "
          f"overall speedup={overall:.2f}x")

    return 0


if __name__ == "__main__":
    sys.exit(main())
